
/// Generated by: MAX11300/1 Configuration Software (Ver. 1.1.0.4) 31/07/2016 13:08
/// Description: MAXREFDES130#
/// Port P0: DAC
/// Port P1: DAC
/// Port P2: DAC
/// Port P3: DAC
/// Port P4: DAC
/// Port P5: DAC
/// Port P6: DAC
/// Port P7: DAC
/// Port P8: DAC
/// Port P9: GPO
/// Port P10: GPO
/// Port P11: GPO
/// Port P12: Single Ended ADC
/// Port P13: N.C.
/// Port P14: N.C.
/// Port P15: N.C.
/// Port P16: N.C.
/// Port P17: N.C.
/// Port P18: N.C.
/// Port P19: N.C.
/// Notes: Header file for MAX11300 configuration used in MAXREFDES130#
#ifndef _MAX11300_DESIGNVALUE_H_
#define _MAX11300_DESIGNVALUE_H_

/// SPI first byte when writing MAX11300 (7-bit address in bits 0x7E; LSB=0 for write)
#define MAX11300Addr_SPI_Write(RegAddr) ( (RegAddr << 1)     )

/// SPI first byte when reading MAX11300 (7-bit address in bits 0x7E; LSB=1 for read)
#define MAX11300Addr_SPI_Read(RegAddr)  ( (RegAddr << 1) | 1 )

/// MAX11300EVKIT Register Addresses
typedef enum MAX11300RegAddressEnum {

/// 0x00 r/o dev_id Device Identification
dev_id = 0x00,

/// 0x01 r/o interrupt_flag Interrupt flags
interrupt_flag = 0x01,

/// 0x02 r/o adc_status_10_to_0 new ADC data available
adc_status_10_to_0 = 0x02,

/// 0x03 r/o adc_status_11 new ADC data available
adc_status_11 = 0x03,

/// 0x04 r/o dac_oi_status_10_to_0 DAC Overcurrent Interrupt
dac_oi_status_10_to_0 = 0x04,

/// 0x05 r/o dac_oi_status_19_to_16 DAC Overcurrent Interrupt
dac_oi_status_11 = 0x05,

/// 0x06 r/o gpi_status_10_to_0 GPI event ready
 gpi_status_10_to_0 = 0x06,

/// 0x07 r/o gpi_status_11 GPI event ready
gpi_status_11 = 0x07,

/// 0x08 r/o tmp_int_data Internal Temeprature
tmp_int_data = 0x08,

/// 0x09 r/o tmp_ext1_data External Temperature D0P/D0N
tmp_ext1_data = 0x09,

/// 0x0a r/o tmp_ext2_data External Temperature D1P/D1N
tmp_ext2_data = 0x0a,

/// 0x0b r/o gpi_data_10_to_0 GPI input ports data
gpi_data_10_to_0 = 0x0b,

/// 0x0c r/o gpi_data_11 GPI input ports data
gpi_data_11 = 0x0c,

/// 0x0d r/w gpo_data_10_to_0 GPO output ports data
gpo_data_10_to_0 = 0x0d,

/// 0x0e r/w gpo_data_11 GPO output ports data
gpo_data_11 = 0x0e,

/// 0x0f r/o reserved_0F reserved
reserved_0F = 0x0f,

/// 0x10 r/w device_control Global device control register
device_control = 0x10,

/// 0x11 r/w interrupt_mask interrupt mask (1 = disable interrupt source)
interrupt_mask = 0x11,

/// 0x12 r/w gpi_irqmode_5_to_0 xxxxxx
gpi_irqmode_5_to_0 = 0x12,

/// 0x13 r/w gpi_irqmode_10_to_6 xxxxxx
gpi_irqmode_10_to_6 = 0x13,

/// 0x14 r/w gpi_irqmode_11 xxxxxx
gpi_irqmode_11 = 0x14,

/// 0x15
reserved_15 = 0x15,

/// 0x16 r/w dac_preset_data_1 DAC preset activated by <see cref="device_control"/>
dac_preset_data_1 = 0x16,

/// 0x17 r/w dac_preset_data_2 DAC preset activated by <see cref="device_control"/>
dac_preset_data_2 = 0x17,

/// 0x18 r/w tmp_mon_cfg Temperautre Monitor Configuration
tmp_mon_cfg = 0x18,

/// 0x19 r/w tmp_mon_int_hi_thresh Internal Temeprature Hot Threshold
tmp_mon_int_hi_thresh = 0x19,

/// 0x1a r/w tmp_mon_int_lo_thresh Internal Temeprature Cold Threshold
tmp_mon_int_lo_thresh = 0x1a,

/// 0x1b r/w tmp_mon_ext1_hi_thresh External Temperature D0P/D0N Hot Threshold
tmp_mon_ext1_hi_thresh = 0x1b,

/// 0x1c r/w tmp_mon_ext1_lo_thresh External Temperature D0P/D0N Cold Threshold
tmp_mon_ext1_lo_thresh = 0x1c,

/// 0x1d r/w tmp_mon_ext2_hi_thresh External Temperature D1P/D1N Hot Threshold
tmp_mon_ext2_hi_thresh = 0x1d,

/// 0x1e r/w tmp_mon_ext2_lo_thresh External Temperature D1P/D1N Cold Threshold
tmp_mon_ext2_lo_thresh = 0x1e,

/// 0x1f r/w reserved_1F reserved
reserved_1F = 0x1f,

reserved_20 = 0x20,
reserved_21 = 0x21,

/// 0x22 r/w port_cfg_00 PIXI Port 0 configuration register
port_cfg_00 = 0x22,

/// 0x23 r/w port_cfg_01 PIXI Port 1 configuration register
port_cfg_01 = 0x23,

/// 0x24 r/w port_cfg_02 PIXI Port 2 configuration register
port_cfg_02 = 0x24,

/// 0x25 r/w port_cfg_03 PIXI Port 3 configuration register
port_cfg_03 = 0x25,

/// 0x26 r/w port_cfg_04 PIXI Port 4 configuration register
port_cfg_04 = 0x26,

/// 0x27 r/w port_cfg_05 PIXI Port 5 configuration register
port_cfg_05 = 0x27,

reserved_28 = 0x28,
reserved_29 = 0x29,
reserved_2a = 0x2a,

/// 0x2b r/w port_cfg_06 PIXI Port 6 configuration register
port_cfg_06 = 0x2b,

/// 0x2c r/w port_cfg_07 PIXI Port 7 configuration register
port_cfg_07 = 0x2c,

/// 0x2d r/w port_cfg_08 PIXI Port 8 configuration register
port_cfg_08 = 0x2d,

/// 0x2e r/w port_cfg_09 PIXI Port 9 configuration register
port_cfg_09 = 0x2e,

/// 0x2f r/w port_cfg_10 PIXI Port 10 configuration register
port_cfg_10 = 0x2f,

/// 0x30 r/w port_cfg_11 PIXI Port 11 configuration register
port_cfg_11 = 0x30,

reserved_31 = 0x31,
reserved_32 = 0x32,
reserved_33 = 0x33,
reserved_40 = 0x40,
reserved_41 = 0x41,

/// 0x42 r/o adc_data_port_00 PIXI Port 0 Analog to Digital Converter register
adc_data_port_00 = 0x42,

/// 0x43 r/o adc_data_port_01 PIXI Port 1 Analog to Digital Converter register
adc_data_port_01 = 0x43,

/// 0x44 r/o adc_data_port_02 PIXI Port 2 Analog to Digital Converter register
adc_data_port_02 = 0x44,

/// 0x45 r/o adc_data_port_03 PIXI Port 3 Analog to Digital Converter register
adc_data_port_03 = 0x45,

/// 0x46 r/o adc_data_port_04 PIXI Port 4 Analog to Digital Converter register
adc_data_port_04 = 0x46,

/// 0x47 r/o adc_data_port_05 PIXI Port 5 Analog to Digital Converter register
adc_data_port_05 = 0x47,

reserved_48 = 0x48,
reserved_49 = 0x49,
reserved_4a = 0x4a,

/// 0x4b r/o adc_data_port_06 PIXI Port 6 Analog to Digital Converter register
adc_data_port_06 = 0x4b,

/// 0x4c r/o adc_data_port_07 PIXI Port 7 Analog to Digital Converter register
adc_data_port_07 = 0x4c,

/// 0x4d r/o adc_data_port_08 PIXI Port 8 Analog to Digital Converter register
adc_data_port_08 = 0x4d,

/// 0x4e r/o adc_data_port_09 PIXI Port 9 Analog to Digital Converter register
adc_data_port_09 = 0x4e,

/// 0x4f r/o adc_data_port_10 PIXI Port 10 Analog to Digital Converter register
adc_data_port_10 = 0x4f,

/// 0x50 r/o adc_data_port_11 PIXI Port 11 Analog to Digital Converter register
adc_data_port_11 = 0x50,

reserved_51 = 0x51,
reserved_52 = 0x52,
reserved_53 = 0x53,
reserved_60 = 0x60,
reserved_61 = 0x61,

/// 0x62 r/w dac_data_port_00 PIXI Port 0 Digital to Analog Converter register
dac_data_port_00 = 0x62,

/// 0x63 r/w dac_data_port_01 PIXI Port 1 Digital to Analog Converter register
dac_data_port_01 = 0x63,

/// 0x64 r/w dac_data_port_02 PIXI Port 2 Digital to Analog Converter register
dac_data_port_02 = 0x64,

/// 0x65 r/w dac_data_port_03 PIXI Port 3 Digital to Analog Converter register
dac_data_port_03 = 0x65,

/// 0x66 r/w dac_data_port_04 PIXI Port 4 Digital to Analog Converter register
dac_data_port_04 = 0x66,

/// 0x67 r/w dac_data_port_05 PIXI Port 5 Digital to Analog Converter register
dac_data_port_05 = 0x67,

reserved_68 = 0x68,
reserved_69 = 0x69,
reserved_6a = 0x6a,

/// 0x6b r/w dac_data_port_06 PIXI Port 6 Digital to Analog Converter register
dac_data_port_06 = 0x6b,

/// 0x6c r/w dac_data_port_07 PIXI Port 7 Digital to Analog Converter register
dac_data_port_07 = 0x6c,

/// 0x6d r/w dac_data_port_08 PIXI Port 8 Digital to Analog Converter register
dac_data_port_08 = 0x6d,

/// 0x6e r/w dac_data_port_09 PIXI Port 9 Digital to Analog Converter register
dac_data_port_09 = 0x6e,

/// 0x6f r/w dac_data_port_10 PIXI Port 10 Digital to Analog Converter register
dac_data_port_10 = 0x6f,

/// 0x70 r/w dac_data_port_11 PIXI Port 11 Digital to Analog Converter register
dac_data_port_11 = 0x70,


} MAX11300RegAddress_t;

/// 0x00 r/o dev_id Device Identification
/// <code>1111xxxxxxxxxxxx</code> PART Part field
/// <code>xxxx11xxxxxxxxxx</code> REV Revision
/// <code>xxxxxx11xxxxxxxx</code> IFMODE Inteface Mode
/// <code>xxxxxxxx11xxxxxx</code> IFSP Inteface Speed
/// <code>xxxxxxxxxx11xxxx</code> NBRPRTS Number of ports
/// <code>xxxxxxxxxxxx11xx</code> RES Resolution
/// <code>xxxxxxxxxxxxxx11</code> VRNG Voltage Range
#define dev_id_PART 	0xf000
#define dev_id_REV 	0x0c00
#define dev_id_IFMODE 	0x0300
#define dev_id_IFSP 	0x00c0
#define dev_id_NBRPRTS 	0x0030
#define dev_id_RES 	0x000c
#define dev_id_VRNG 	0x0003

/// 0x01 r/o interrupt_flag Interrupt flags
/// <code>1xxxxxxxxxxxxxxx</code> VMON High Voltage Supply Monitor
/// <code>x1xxxxxxxxxxxxxx</code> TMPEXT2HOT External Temperature D1P/D1N Hot
/// <code>xx1xxxxxxxxxxxxx</code> TMPEXT2COLD External Temperature D1P/D1N Cold
/// <code>xxx1xxxxxxxxxxxx</code> TMPEXT2NEW External Temperature D1P/D1N New
/// <code>xxxx1xxxxxxxxxxx</code> TMPEXT1HOT External Temperature D0P/D0N Hot
/// <code>xxxxx1xxxxxxxxxx</code> TMPEXT1COLD External Temperature D0P/D0N Cold
/// <code>xxxxxx1xxxxxxxxx</code> TMPEXT1NEW External Temperature D0P/D0N New
/// <code>xxxxxxx1xxxxxxxx</code> TMPINTHOT Internal Temeprature Hot
/// <code>xxxxxxxx1xxxxxxx</code> TMPINTCOLD Internal Temeprature Cold
/// <code>xxxxxxxxx1xxxxxx</code> TMPINTNEW Internal Temeprature New
/// <code>xxxxxxxxxx1xxxxx</code> DACOI DAC over-current
/// <code>xxxxxxxxxxx1xxxx</code> GPIDM GPI event missed
/// <code>xxxxxxxxxxxx1xxx</code> GPIDR GPI event ready
/// <code>xxxxxxxxxxxxx1xx</code> ADCDM ADC data missed
/// <code>xxxxxxxxxxxxxx1x</code> ADCDR ADC data ready
/// <code>xxxxxxxxxxxxxxx1</code> ADCFLAG ADC conversion/sweep complete
#define interrupt_flag_VMON 	0x8000
#define interrupt_flag_TMPEXT2HOT 	0x4000
#define interrupt_flag_TMPEXT2COLD 	0x2000
#define interrupt_flag_TMPEXT2NEW 	0x1000
#define interrupt_flag_TMPEXT1HOT 	0x0800
#define interrupt_flag_TMPEXT1COLD 	0x0400
#define interrupt_flag_TMPEXT1NEW 	0x0200
#define interrupt_flag_TMPINTHOT 	0x0100
#define interrupt_flag_TMPINTCOLD 	0x0080
#define interrupt_flag_TMPINTNEW 	0x0040
#define interrupt_flag_DACOI 	0x0020
#define interrupt_flag_GPIDM 	0x0010
#define interrupt_flag_GPIDR 	0x0008
#define interrupt_flag_ADCDM 	0x0004
#define interrupt_flag_ADCDR 	0x0002
#define interrupt_flag_ADCFLAG 	0x0001

/// 0x02 r/o adc_status_10_to_0 new ADC data available
#define adc_status_10_to_0_ADCST10 	0x8000
#define adc_status_10_to_0_ADCST09 	0x4000
#define adc_status_10_to_0_ADCST08 	0x2000
#define adc_status_10_to_0_ADCST07 	0x1000
#define adc_status_10_to_0_ADCST06 	0x0800
#define adc_status_10_to_0_ADCST05 	0x0080
#define adc_status_10_to_0_ADCST04 	0x0040
#define adc_status_10_to_0_ADCST03 	0x0020
#define adc_status_10_to_0_ADCST02 	0x0010
#define adc_status_10_to_0_ADCST01 	0x0008
#define adc_status_10_to_0_ADCST00 	0x0004

/// 0x03 r/o adc_status_19_to_16 new ADC data available
#define adc_status_11_ADCST11 	    0x0001

/// 0x04 r/o dac_oi_status_15_to_0 DAC Overcurrent Interrupt
#define dac_oi_status_10_to_0_DACOIST10 	0x8000
#define dac_oi_status_10_to_0_DACOIST09 	0x4000
#define dac_oi_status_10_to_0_DACOIST08 	0x2000
#define dac_oi_status_10_to_0_DACOIST07 	0x1000
#define dac_oi_status_10_to_0_DACOIST06 	0x0800
#define dac_oi_status_10_to_0_DACOIST05 	0x0080
#define dac_oi_status_10_to_0_DACOIST04 	0x0040
#define dac_oi_status_10_to_0_DACOIST03 	0x0020
#define dac_oi_status_10_to_0_DACOIST02 	0x0010
#define dac_oi_status_10_to_0_DACOIST01 	0x0008
#define dac_oi_status_10_to_0_DACOIST00 	0x0004

/// 0x05 r/o dac_oi_status_19_to_16 DAC Overcurrent Interrupt
#define dac_oi_status_11_DACOIST11 	0x0001

/// 0x06 r/o gpi_status_15_to_0 GPI event ready
#define gpi_status_10_to_0_GPIST10 	0x8000
#define gpi_status_10_to_0_GPIST09 	0x4000
#define gpi_status_10_to_0_GPIST08 	0x2000
#define gpi_status_10_to_0_GPIST07 	0x1000
#define gpi_status_10_to_0_GPIST06 	0x0800
#define gpi_status_10_to_0_GPIST05 	0x0080
#define gpi_status_10_to_0_GPIST04 	0x0040
#define gpi_status_10_to_0_GPIST03 	0x0020
#define gpi_status_10_to_0_GPIST02 	0x0010
#define gpi_status_10_to_0_GPIST01 	0x0008
#define gpi_status_10_to_0_GPIST00 	0x0004

/// 0x07 r/o gpi_status_19_to_16 GPI event ready
#define gpi_status_11_GPIST11 	0x0001

/// 0x08 r/o tmp_int_data Internal Temeprature
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_int_data_tempcode 	0x0fff

/// 0x09 r/o tmp_ext1_data External Temperature D0P/D0N
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_ext1_data_tempcode 	0x0fff

/// 0x0a r/o tmp_ext2_data External Temperature D1P/D1N
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_ext2_data_tempcode 	0x0fff

/// 0x0b r/o gpi_data_15_to_0 GPI input ports data
#define gpi_data_10_to_0_GPIDAT10 	0x8000
#define gpi_data_10_to_0_GPIDAT09 	0x4000
#define gpi_data_10_to_0_GPIDAT08 	0x2000
#define gpi_data_10_to_0_GPIDAT07 	0x1000
#define gpi_data_10_to_0_GPIDAT06 	0x0800
#define gpi_data_10_to_0_GPIDAT05 	0x0080
#define gpi_data_10_to_0_GPIDAT04 	0x0040
#define gpi_data_10_to_0_GPIDAT03 	0x0020
#define gpi_data_10_to_0_GPIDAT02 	0x0010
#define gpi_data_10_to_0_GPIDAT01 	0x0008
#define gpi_data_10_to_0_GPIDAT00 	0x0004

/// 0x0c r/o gpi_data_19_to_16 GPI input ports data
#define gpi_data_11_GPIDAT11 	0x0001

/// 0x0d r/w gpo_data_15_to_0 GPO output ports data
#define gpo_data_10_to_0_GPODAT10 	0x8000
#define gpo_data_10_to_0_GPODAT09 	0x4000
#define gpo_data_10_to_0_GPODAT08 	0x2000
#define gpo_data_10_to_0_GPODAT07 	0x1000
#define gpo_data_10_to_0_GPODAT06 	0x0800
#define gpo_data_10_to_0_GPODAT05 	0x0080
#define gpo_data_10_to_0_GPODAT04 	0x0040
#define gpo_data_10_to_0_GPODAT03 	0x0020
#define gpo_data_10_to_0_GPODAT02 	0x0010
#define gpo_data_10_to_0_GPODAT01 	0x0008
#define gpo_data_10_to_0_GPODAT00 	0x0004
#define gpo_data_10_to_0_DESIGNVALUE 	0x0000

/// 0x0e r/w gpo_data_19_to_16 GPO output ports data
#define gpo_data_11_GPODAT11 	0x0001
#define gpo_data_11_DESIGNVALUE 	0x0000

/// 0x0f r/o reserved_0F reserved


/// 0x10 r/w device_control Global device control register
/// <code>1xxxxxxxxxxxxxxx</code> RESET Soft reset command
/// <code>x1xxxxxxxxxxxxxx</code> BRST Burst Mode
/// <code>xx1xxxxxxxxxxxxx</code> LPEN Low Power Enable
/// <code>xxx1xxxxxxxxxxxx</code> RS_CANCEL series resistance cancelation on external temperature monitors D0P/D0N and D1P/D1N
/// <code>xxxx1xxxxxxxxxxx</code> TMPPER temperature monitor period
/// <code>xxxxx1xxxxxxxxxx</code> TMPCTLEXT1 monitor external temperature D1P/D1N
/// <code>xxxxxx1xxxxxxxxx</code> TMPCTLEXT0 monitor external temperature D0P/D0N
/// <code>xxxxxxx1xxxxxxxx</code> TMPCTLINT monitor internal temperature
/// <code>xxxxxxxx1xxxxxxx</code> THSHDN Thermal Shutdown
/// <code>xxxxxxxxx1xxxxxx</code> DACREF DAC voltage reference
/// <code>xxxxxxxxxx11xxxx</code> ADCCONV ADC conversion rate
/// <code>xxxxxxxxxxxx11xx</code> DACCTL DAC update mode
/// <code>xxxxxxxxxxxxxx11</code> ADCCTL ADC conversion mode
#define device_control_RESET 	0x8000
#define device_control_BRST 	0x4000
#define device_control_LPEN 	0x2000
#define device_control_RS_CANCEL 	0x1000
#define device_control_TMPPER 	0x0800
#define device_control_TMPCTLEXT1 	0x0400
#define device_control_TMPCTLEXT0 	0x0200
#define device_control_TMPCTLINT 	0x0100
#define device_control_THSHDN 	0x0080
#define device_control_DACREF 	0x0040
#define device_control_ADCCONV 	0x0030
#define device_control_DACCTL 	0x000c
#define device_control_ADCCTL 	0x0003
#define device_control_DESIGNVALUE 	0x00f2

/// 0x11 r/w interrupt_mask interrupt mask (1 = disable interrupt source)
/// <code>1xxxxxxxxxxxxxxx</code> VMON High Voltage Supply Monitor
/// <code>x1xxxxxxxxxxxxxx</code> TMPEXT2HOT External Temperature D1P/D1N Hot
/// <code>xx1xxxxxxxxxxxxx</code> TMPEXT2COLD External Temperature D1P/D1N Cold
/// <code>xxx1xxxxxxxxxxxx</code> TMPEXT2NEW External Temperature D1P/D1N New
/// <code>xxxx1xxxxxxxxxxx</code> TMPEXT1HOT External Temperature D0P/D0N Hot
/// <code>xxxxx1xxxxxxxxxx</code> TMPEXT1COLD External Temperature D0P/D0N Cold
/// <code>xxxxxx1xxxxxxxxx</code> TMPEXT1NEW External Temperature D0P/D0N New
/// <code>xxxxxxx1xxxxxxxx</code> TMPINTHOT Internal Temeprature Hot
/// <code>xxxxxxxx1xxxxxxx</code> TMPINTCOLD Internal Temeprature Cold
/// <code>xxxxxxxxx1xxxxxx</code> TMPINTNEW Internal Temeprature New
/// <code>xxxxxxxxxx1xxxxx</code> DACOI DAC over-current
/// <code>xxxxxxxxxxx1xxxx</code> GPIDM GPI event missed
/// <code>xxxxxxxxxxxx1xxx</code> GPIDR GPI event ready
/// <code>xxxxxxxxxxxxx1xx</code> ADCDM ADC data missed
/// <code>xxxxxxxxxxxxxx1x</code> ADCDR ADC data ready
/// <code>xxxxxxxxxxxxxxx1</code> ADCFLAG ADC conversion/sweep complete
#define interrupt_mask_VMON 	0x8000
#define interrupt_mask_TMPEXT2HOT 	0x4000
#define interrupt_mask_TMPEXT2COLD 	0x2000
#define interrupt_mask_TMPEXT2NEW 	0x1000
#define interrupt_mask_TMPEXT1HOT 	0x0800
#define interrupt_mask_TMPEXT1COLD 	0x0400
#define interrupt_mask_TMPEXT1NEW 	0x0200
#define interrupt_mask_TMPINTHOT 	0x0100
#define interrupt_mask_TMPINTCOLD 	0x0080
#define interrupt_mask_TMPINTNEW 	0x0040
#define interrupt_mask_DACOI 	0x0020
#define interrupt_mask_GPIDM 	0x0010
#define interrupt_mask_GPIDR 	0x0008
#define interrupt_mask_ADCDM 	0x0004
#define interrupt_mask_ADCDR 	0x0002
#define interrupt_mask_ADCFLAG 	0x0001
#define interrupt_mask_DESIGNVALUE 	0xffff

/// 0x12 r/w gpi_irqmode_7_to_0 xxxxxx
#define gpi_irqmode_5_to_0_GPIMD05 	0xc000
#define gpi_irqmode_5_to_0_GPIMD04 	0x3000
#define gpi_irqmode_5_to_0_GPIMD03 	0x0c00
#define gpi_irqmode_5_to_0_GPIMD02 	0x0300
#define gpi_irqmode_5_to_0_GPIMD01 	0x00c0
#define gpi_irqmode_5_to_0_GPIMD00 	0x0030
#define gpi_irqmode_5_to_0_DESIGNVALUE 	0x0000

/// 0x13 r/w gpi_irqmode_15_to_8 xxxxxx
#define gpi_irqmode_10_to_6_GPIMD10 	0xc000
#define gpi_irqmode_10_to_6_GPIMD09 	0x3000
#define gpi_irqmode_10_to_6_GPIMD08 	0x0c00
#define gpi_irqmode_10_to_6_GPIMD07 	0x0300
#define gpi_irqmode_10_to_6_GPIMD06 	0x00c0
#define gpi_irqmode_10_to_6_DESIGNVALUE 	0x0000

/// 0x14 r/w gpi_irqmode_19_to_16 xxxxxx
#define gpi_irqmode_11_GPIMD11 	0x0003
#define gpi_irqmode_11_DESIGNVALUE 	0x0000

/// 0x16 r/w dac_preset_data_1 DAC preset activated by <see cref="device_control"/>
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_preset_data_1_daccode 	0x0fff
#define dac_preset_data_1_DESIGNVALUE 	0x0000

/// 0x17 r/w dac_preset_data_2 DAC preset activated by <see cref="device_control"/>
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_preset_data_2_daccode 	0x0fff
#define dac_preset_data_2_DESIGNVALUE 	0x0000

/// 0x18 r/w tmp_mon_cfg Temperautre Monitor Configuration
/// <code>xxxxxxxxxx11xxxx</code> TMPEXT2MONCFG average 4, 8, 16, or 32 measurements
/// <code>xxxxxxxxxxxx11xx</code> TMPEXT1MONCFG average 4, 8, 16, or 32 measurements
/// <code>xxxxxxxxxxxxxx11</code> TMPINTMONCFG average 4, 8, 16, or 32 measurements
#define tmp_mon_cfg_TMPEXT2MONCFG 	0x0030
#define tmp_mon_cfg_TMPEXT1MONCFG 	0x000c
#define tmp_mon_cfg_TMPINTMONCFG 	0x0003

/// 0x19 r/w tmp_mon_int_hi_thresh Internal Temeprature Hot Threshold
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_mon_int_hi_thresh_tempcode 	0x0fff
#define tmp_mon_int_hi_thresh_DESIGNVALUE 	0x07ff

/// 0x1a r/w tmp_mon_int_lo_thresh Internal Temeprature Cold Threshold
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_mon_int_lo_thresh_tempcode 	0x0fff
#define tmp_mon_int_lo_thresh_DESIGNVALUE 	0x0800

/// 0x1b r/w tmp_mon_ext1_hi_thresh External Temperature D0P/D0N Hot Threshold
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_mon_ext1_hi_thresh_tempcode 	0x0fff
#define tmp_mon_ext1_hi_thresh_DESIGNVALUE 	0x07ff

/// 0x1c r/w tmp_mon_ext1_lo_thresh External Temperature D0P/D0N Cold Threshold
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_mon_ext1_lo_thresh_tempcode 	0x0fff
#define tmp_mon_ext1_lo_thresh_DESIGNVALUE 	0x0800

/// 0x1d r/w tmp_mon_ext2_hi_thresh External Temperature D1P/D1N Hot Threshold
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_mon_ext2_hi_thresh_tempcode 	0x0fff
#define tmp_mon_ext2_hi_thresh_DESIGNVALUE 	0x07ff

/// 0x1e r/w tmp_mon_ext2_lo_thresh External Temperature D1P/D1N Cold Threshold
/// <code>xxxx111111111111</code> tempcode Temperature code, LSB=0.125 degrees C, 12-bit 2's complement
#define tmp_mon_ext2_lo_thresh_tempcode 	0x0fff
#define tmp_mon_ext2_lo_thresh_DESIGNVALUE 	0x0800

/// 0x1f r/w reserved_1F reserved


/// 0x20 r/w port_cfg_00 PIXI Port 0 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_00_PortCfgFuncID 	0xf000
#define port_cfg_00_funcprm_avrInv 	0x0800
#define port_cfg_00_funcprm_range 	0x0700
#define port_cfg_00_funcprm_nsamples 	0x00e0
#define port_cfg_00_funcprm_port 	0x001f
#define port_cfg_00_DESIGNVALUE 	0x5100

/// 0x21 r/w port_cfg_01 PIXI Port 1 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_01_PortCfgFuncID 	0xf000
#define port_cfg_01_funcprm_avrInv 	0x0800
#define port_cfg_01_funcprm_range 	0x0700
#define port_cfg_01_funcprm_nsamples 	0x00e0
#define port_cfg_01_funcprm_port 	0x001f
#define port_cfg_01_DESIGNVALUE 	0x5100

/// 0x22 r/w port_cfg_02 PIXI Port 2 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_02_PortCfgFuncID 	0xf000
#define port_cfg_02_funcprm_avrInv 	0x0800
#define port_cfg_02_funcprm_range 	0x0700
#define port_cfg_02_funcprm_nsamples 	0x00e0
#define port_cfg_02_funcprm_port 	0x001f
#define port_cfg_02_DESIGNVALUE 	0x5100

/// 0x23 r/w port_cfg_03 PIXI Port 3 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_03_PortCfgFuncID 	0xf000
#define port_cfg_03_funcprm_avrInv 	0x0800
#define port_cfg_03_funcprm_range 	0x0700
#define port_cfg_03_funcprm_nsamples 	0x00e0
#define port_cfg_03_funcprm_port 	0x001f
#define port_cfg_03_DESIGNVALUE 	0x5100

/// 0x24 r/w port_cfg_04 PIXI Port 4 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_04_PortCfgFuncID 	0xf000
#define port_cfg_04_funcprm_avrInv 	0x0800
#define port_cfg_04_funcprm_range 	0x0700
#define port_cfg_04_funcprm_nsamples 	0x00e0
#define port_cfg_04_funcprm_port 	0x001f
#define port_cfg_04_DESIGNVALUE 	0x5100

/// 0x25 r/w port_cfg_05 PIXI Port 5 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_05_PortCfgFuncID 	0xf000
#define port_cfg_05_funcprm_avrInv 	0x0800
#define port_cfg_05_funcprm_range 	0x0700
#define port_cfg_05_funcprm_nsamples 	0x00e0
#define port_cfg_05_funcprm_port 	0x001f
#define port_cfg_05_DESIGNVALUE 	0x5100

/// 0x26 r/w port_cfg_06 PIXI Port 6 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_06_PortCfgFuncID 	0xf000
#define port_cfg_06_funcprm_avrInv 	0x0800
#define port_cfg_06_funcprm_range 	0x0700
#define port_cfg_06_funcprm_nsamples 	0x00e0
#define port_cfg_06_funcprm_port 	0x001f
#define port_cfg_06_DESIGNVALUE 	0x5100

/// 0x27 r/w port_cfg_07 PIXI Port 7 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_07_PortCfgFuncID 	0xf000
#define port_cfg_07_funcprm_avrInv 	0x0800
#define port_cfg_07_funcprm_range 	0x0700
#define port_cfg_07_funcprm_nsamples 	0x00e0
#define port_cfg_07_funcprm_port 	0x001f
#define port_cfg_07_DESIGNVALUE 	0x5100

/// 0x28 r/w port_cfg_08 PIXI Port 8 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_08_PortCfgFuncID 	0xf000
#define port_cfg_08_funcprm_avrInv 	0x0800
#define port_cfg_08_funcprm_range 	0x0700
#define port_cfg_08_funcprm_nsamples 	0x00e0
#define port_cfg_08_funcprm_port 	0x001f
#define port_cfg_08_DESIGNVALUE 	0x5100

/// 0x29 r/w port_cfg_09 PIXI Port 9 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_09_PortCfgFuncID 	0xf000
#define port_cfg_09_funcprm_avrInv 	0x0800
#define port_cfg_09_funcprm_range 	0x0700
#define port_cfg_09_funcprm_nsamples 	0x00e0
#define port_cfg_09_funcprm_port 	0x001f
#define port_cfg_09_DESIGNVALUE 	0x3000

/// 0x2a r/w port_cfg_10 PIXI Port 10 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_10_PortCfgFuncID 	0xf000
#define port_cfg_10_funcprm_avrInv 	0x0800
#define port_cfg_10_funcprm_range 	0x0700
#define port_cfg_10_funcprm_nsamples 	0x00e0
#define port_cfg_10_funcprm_port 	0x001f
#define port_cfg_10_DESIGNVALUE 	0x3000

/// 0x2b r/w port_cfg_11 PIXI Port 11 configuration register
/// <code>1111xxxxxxxxxxxx</code> PortCfgFuncID Port function / mode
/// <code>xxxx1xxxxxxxxxxx</code> funcprm_avrInv AVR / INV
/// <code>xxxxx111xxxxxxxx</code> funcprm_range DAC Range / ADC Range
/// <code>xxxxxxxx111xxxxx</code> funcprm_nsamples Number of samples / CAP
/// <code>xxxxxxxxxxx11111</code> funcprm_port Associated port 0..31
#define port_cfg_11_PortCfgFuncID 	0xf000
#define port_cfg_11_funcprm_avrInv 	0x0800
#define port_cfg_11_funcprm_range 	0x0700
#define port_cfg_11_funcprm_nsamples 	0x00e0
#define port_cfg_11_funcprm_port 	0x001f
#define port_cfg_11_DESIGNVALUE 	0x3000


/// 0x40 r/o adc_data_port_00 PIXI Port 0 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_00_adccode 	0x0fff

/// 0x41 r/o adc_data_port_01 PIXI Port 1 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_01_adccode 	0x0fff

/// 0x42 r/o adc_data_port_02 PIXI Port 2 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_02_adccode 	0x0fff

/// 0x43 r/o adc_data_port_03 PIXI Port 3 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_03_adccode 	0x0fff

/// 0x44 r/o adc_data_port_04 PIXI Port 4 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_04_adccode 	0x0fff

/// 0x45 r/o adc_data_port_05 PIXI Port 5 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_05_adccode 	0x0fff

/// 0x46 r/o adc_data_port_06 PIXI Port 6 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_06_adccode 	0x0fff

/// 0x47 r/o adc_data_port_07 PIXI Port 7 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_07_adccode 	0x0fff

/// 0x48 r/o adc_data_port_08 PIXI Port 8 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_08_adccode 	0x0fff

/// 0x49 r/o adc_data_port_09 PIXI Port 9 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_09_adccode 	0x0fff

/// 0x4a r/o adc_data_port_10 PIXI Port 10 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_10_adccode 	0x0fff

/// 0x4b r/o adc_data_port_11 PIXI Port 11 Analog to Digital Converter register
/// <code>xxxx111111111111</code> adccode 12-bit ADC code
#define adc_data_port_11_adccode 	0x0fff

/// 0x60 r/w dac_data_port_00 PIXI Port 0 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_00_daccode 	0x0fff
#define dac_data_port_00_DESIGNVALUE 	0x0000

/// 0x61 r/w dac_data_port_01 PIXI Port 1 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_01_daccode 	0x0fff
#define dac_data_port_01_DESIGNVALUE 	0x0000

/// 0x62 r/w dac_data_port_02 PIXI Port 2 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_02_daccode 	0x0fff
#define dac_data_port_02_DESIGNVALUE 	0x0000

/// 0x63 r/w dac_data_port_03 PIXI Port 3 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_03_daccode 	0x0fff
#define dac_data_port_03_DESIGNVALUE 	0x0000

/// 0x64 r/w dac_data_port_04 PIXI Port 4 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_04_daccode 	0x0fff
#define dac_data_port_04_DESIGNVALUE 	0x0000

/// 0x65 r/w dac_data_port_05 PIXI Port 5 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_05_daccode 	0x0fff
#define dac_data_port_05_DESIGNVALUE 	0x0000

/// 0x66 r/w dac_data_port_06 PIXI Port 6 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_06_daccode 	0x0fff
#define dac_data_port_06_DESIGNVALUE 	0x0000

/// 0x67 r/w dac_data_port_07 PIXI Port 7 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_07_daccode 	0x0fff
#define dac_data_port_07_DESIGNVALUE 	0x0000

/// 0x68 r/w dac_data_port_08 PIXI Port 8 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_08_daccode 	0x0fff
#define dac_data_port_08_DESIGNVALUE 	0x0000

/// 0x69 r/w dac_data_port_09 PIXI Port 9 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_09_daccode 	0x0fff
#define dac_data_port_09_DESIGNVALUE 	0x0800

/// 0x6a r/w dac_data_port_10 PIXI Port 10 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_10_daccode 	0x0fff
#define dac_data_port_10_DESIGNVALUE 	0x0800

/// 0x6b r/w dac_data_port_11 PIXI Port 11 Digital to Analog Converter register
/// <code>xxxx111111111111</code> daccode 12-bit DAC code
#define dac_data_port_11_daccode 	0x0fff
#define dac_data_port_11_DESIGNVALUE 	0x0800

#endif /* _MAX11300_DESIGNVALUE_H_ */

// End of file
